# Generated by Django 3.0.5 on 2020-05-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20200502_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='problems.Problem'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='problems.Category'),
        ),
    ]
